### ISSUE TITLE
Rewrite Pending

### ISSUE THREAD

**Issue by xcf-t** [NobodyMiner/minecraft-client#5]
### TODO:

- [ ] Install Minecraft
   - [ ] Download Assets
   - [ ] Download Libraries
- [ ] Allow instances
   - [ ] Possibility to save/load instances
- [ ] Install Forge
- [ ] Install Liteloader
- [ ] Optimize Downloads
   - [ ] Implement Cache
- [ ] Authentication

### Later:

- [ ] Ability to import modpacks
   - [ ] MPF-Format
   - [ ] CurseForge-Format
- [ ] Ability to install mods by id
   - [ ] [CurseMeta](https://www.npmjs.com/package/cursemeta)
- [ ] Some more stuff I can't remember

![Flowchart](https://i.imgur.com/u8QRD5Z.png)
